apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: zad4
spec:
  replicas: 3
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 250Mi
            cpu: 250m
          requests:
            memory: 150Mi
            cpu: 150m

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: zad4
spec:
  selector:
    run: php-apache
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
